<a href="https://colab.research.google.com/github/Srivikkash/python-ml/blob/main/python_an_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/dataset/Housing2.csv")

In [ ]:
x=data[['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus']]
y=data.price

In [ ]:
# sns.pairplot(data)  ##ploting integer values in a graph

Training


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
model = LinearRegression()

In [ ]:
ft=model.fit(x_train,y_train) ##train_model_fit


In [ ]:
ft.score(x_train,y_train) ##train_score

0.6910958813736235

predict train data


In [ ]:
y_train_pred = ft.predict(x_train)

In [ ]:
y_train_pred 

array([ 3851797.59225869,  4889437.40027199,  4229931.08878954,
        5041855.29055867,  2607838.72325482,  3801158.72913131,
        4035001.42182298,  5197976.32485833,  6736424.77124224,
        3647751.69641809,  2366257.75026349,  6568383.44669195,
        7416724.035786  ,  4361760.48263097,  3410618.78493972,
        7358732.84241177,  7021610.66412869,  3881883.57743682,
        3243296.64300935,  3361219.98534223,  4006061.00041476,
        8350365.4083599 ,  7223588.04006343,  3225561.82512621,
        2988725.09616902,  3604165.44969774,  2763353.50632539,
        4394523.80465573,  3542128.56483067,  4850833.21363405,
        7509694.2083229 ,  5465124.91422605,  5228497.33374814,
        3532443.23165034,  3493155.76733012,  3731640.01814447,
        4574663.59449252,  4933063.41796471,  2046001.75238324,
        4384615.51246449,  5877521.89733149,  5752787.16995954,
        6556918.84044582,  3407194.27170356,  2691564.17090412,
        4006962.21745062,  3353171.61807

predict test data

In [ ]:
y_test_pred = ft.predict(x_test)

In [ ]:
y_test_pred

array([3468746.27847185, 6277047.74573103, 6790205.91833889,
       6486218.81044819, 7025332.12547707, 3623426.06460216,
       4768001.83879902, 4655374.769298  , 7200051.81946613,
       2193003.77963999, 5789743.5193137 , 3073278.9554063 ,
       4031864.63608675, 5597952.99401406, 3305698.62931622,
       5041002.99091479, 4424653.95084195, 3049605.36143838,
       6328007.03125866, 6433261.12917397, 6915858.91036763,
       7168610.63862037, 3166749.34253821, 2889368.35183002,
       5943703.66200319, 6438504.87434324, 4239960.49479381,
       8078616.23682485, 3617356.14341151, 3578247.13341705,
       7739036.72904988, 5934206.49918819, 2035566.5092897 ,
       5784517.99055802, 6066458.0566772 , 6380997.7539214 ,
       4349222.9386702 , 2511677.49961338, 3511066.33845103,
       2803628.79115383, 5215607.63557852, 6708815.35855399,
       5126384.96122276, 3788173.31967299, 5737184.27810062,
       2633926.83098867, 4776319.32298895, 3253145.17617871,
       3201190.89566138,

In [ ]:
ft.score(x_test,y_test)

0.5966544978020039

In [ ]:
x_test

new predict


In [ ]:
new=np.array([[8580,4,3,4,1,0,0,0,1,2,1,2]])
ft.predict(new)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([10148324.83898599])